apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apacheapp-deploy
  name: apacheapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apacheapp-pod
  template:
    metadata:
      labels:
        app: apacheapp-pod
    spec:
      containers:
      - image: "<repo-name>/cloud-native-spoke/cloud-native-repo/httpd:v1.0"
        name: apacheapp
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: apacheapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apacheapp-pod
  type: ClusterIP
