apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuretogkela-deploy
spec:
  selector:
    matchLabels:
      greeting: azuretogkela-pod
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        greeting: azuretogkela-pod
        version: v1
    spec:
      containers:
      - name: azuretogkela
        image: "gkewkshpacr.azurecr.io/azuretogkela:v1.0.0"
        imagePullPolicy: Always      
        # resources:
        #   requests:
        #     cpu: "0.1"
        #     memory: "256Mi"
        #   limits:
        #     cpu: "0.2"
        #     memory: "512Mi"
        envFrom:
        - secretRef:
            name: logicapp-secret
      imagePullSecrets:
      - name: gkewkshpacr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: azuretogkela-svc
spec:
  type: ClusterIP
  selector:    
    version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
