apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig
spec:
  timeoutSec: 40
  connectionDraining:
    drainingTimeoutSec: 60
  customRequestHeaders:
    headers:
    - "X-Client-Geo-Location:{client_region},{client_city}"