apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxapp-deploy  
spec:
  selector:
    matchLabels:
      greeting: nginxapp-pod
      version: "1.0"
  replicas: 1
  template:
    metadata:
      labels:
        greeting: nginxapp-pod
        version: "1.0"
    spec:
      containers:
      - name: nginxapp
        image: "<repo-name>/cloud-native-spoke/cloud-native-repo/nginx-app:v1.0"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxapp-svc
  # annotations:
  #   cloud.google.com/backend-config: '{"default": "my-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    greeting: nginxapp-pod
    version: "1.0"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
