apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: sqlconnectarcapp-deploy
  name: sqlconnectarcapp-deploy
  namespace: apis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlconnectarcapp-deploy  
  template:
    metadata:      
      labels:
        app: sqlconnectarcapp-deploy
    spec:
      containers:
      - image: gkewkshpacr.azurecr.io/sqlconnectarcapp:v1.0.0
        name: sqlconnectarcapp
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: 250Mi
          limits:
            cpu: "1"
            memory: 500Mi
        envFrom:
        - secretRef:
            name: sqlconn-secret
      imagePullSecrets:
      - name: gkewkshpacr-secret
---
apiVersion: v1
kind: Service
metadata:  
  labels:
    app: sqlconnectarcapp-deploy
  name: sqlconnectarcapp-svc
  namespace: apis
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sqlconnectarcapp-deploy
  type: ClusterIP