apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app-deploy
spec:
  selector:
    matchLabels:
      greeting: hello-app
      version: "1.0"
  replicas: 1
  template:
    metadata:
      labels:
        greeting: hello-app
        version: "1.0"
    spec:
      containers:
      - name: hello-app-cntr
        image: "<artifact-reg-name>/cloud-native-repo/hello-app:v1.0"
        env:
        - name: PORT
          value: "50000"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-app
spec:
  type: ClusterIP
  selector:
    greeting: hello-app
    version: "1.0"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50000
