apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment-1
spec:
  selector:
    matchLabels:
      greeting: hello
      version: one
  replicas: 1
  template:
    metadata:
      labels:
        greeting: hello
        version: one
    spec:
      containers:
      - name: hello-app-1
        image: "us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0"
        env:
        - name: "PORT"
          value: "50000"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-1
spec:
  type: ClusterIP
  selector:
    greeting: hello
    version: one
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50000
